language: swift # or objective-c
osx_image: xcode8.2
script:
  - xcodebuild -scheme Weatherman -workspace Weatherman.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=10' build test
after_success:
    - bash <(curl -s https://codecov.io/bash) -J 'weatherman-ios'

